### PR TITLE
feat: djust init and a three-command djust new

### PR DESCRIPTION
**Pull request by johnrtipton**
## Summary

The installation page asked new users to run nine commands and read two recovery sections. After this change, the paths are:

```bash
uvx djust@latest new myproject && cd myproject && make dev   # new project
uvx djust@latest init                                         # existing Django project
```

**`djust new`**
- The generated `Makefile` calls `.venv/bin/python`, so `make dev` works without activating the environment. An exported `PYTHON` variable no longer overrides it.
- Setup pins a supported Python (`uv venv --python ">=3.10"`) and finishes with `manage.py check`.
- The success output prints exact next steps, including Windows and `--no-setup`.
- `requirements.txt` sets its minimum djust to the version that generated the project, instead of `djust>=0.3.0`.

**`djust init`** (new: `python/djust/scaffolding/init_project.py`)
- **Settings:** appends a marked, idempotent block to settings. It adds `channels`/`djust` to `INSTALLED_APPS` (AppConfig paths count as already present) and sets `ASGI_APPLICATION` and an in-memory `CHANNEL_LAYERS` (unless one is configured). **It does not change `TEMPLATES`** (see below).
- **ASGI:** replaces `asgi.py` only when its syntax tree matches Django's stock file for the same settings module. Otherwise it prints the code to merge and exits 2.
- **Packages:** `uv add` for uv projects. For `requirements.txt` projects it adds missing lines (following `-r` includes; editable, URL and `name @ url` forms count as present) and installs into the project's own `.venv` only. For Poetry or no manifest it prints a shell-quoted command.
- **Check:** runs `manage.py check` after installing.
- **Safety:** refuses files with uncommitted git changes unless `--force`. `--dry-run` prints the diff and exits 0. Settings packages (`mysite/settings/`, `config.settings.local`) are refused with the block to paste. CRLF line endings are preserved.
- **Exit codes:** 0 done, 1 refused before writing, 2 wrote files but something needs attention.

**Docs:** `installation.md` now leads with the two commands. It keeps the step-by-step setup as "Configure by hand" and moves the recovery material into a Troubleshooting section. `guides/scaffolding.md` gains a `djust init` reference.

### Why `init` leaves `TEMPLATES` alone

With `DjustTemplateBackend` first and `APP_DIRS: True` (the shape C016 recommends and `djust new --with-db` generates), the admin changelist and change pages raise `'DjustTemplateBackend' object has no attribute 'select_template'`. That is filed as #2872.

LiveViews don't need the backend. They read template source through `loader.get_template(...).template.source` and render it in Rust whichever engine found the file. I verified this with the Your First LiveView counter clicking in a browser, with no djust entry in `TEMPLATES`. The startproject → `init` test now also loads the admin list and edit pages.

### Branch base

This branch is based on `codex/markdown-editor-guide-readability`, whose 4 commits were never pushed. It carries them:

| Commit | What it does |
|---|---|
| `9a8f4178` | markdown editor docs |
| `1a24cb16`, `6ca197c3` | the install-doc rewrite this work builds on |
| `b6d01e94` | makes scaffold setup target the new `.venv` and stop on failure; this work depends on it |

The docs describe unreleased CLI behaviour. Both docs sites render a pinned release, so the new page goes live with the release that ships the CLI.

## Test plan

- [x] `python/djust/tests/test_djust_init.py` (new, 60+ cases) and `test_scaffold_setup_environment.py`.
- [x] Every test failed before its fix. Targeted gate-off mutations (28 total, the mutation-applied check enforced) were all caught.
- [x] Full suite across `tests/ python/tests/ python/djust/tests/` after merging `origin/main`: 27,447 passed, 0 failed.
- [x] Manual, with an unrelated `VIRTUAL_ENV` active, using this branch's CLI:
  - `djust new demo` → `make dev` → `/` and `client.js` 200; adding a starter-list item updates live in Chrome.
  - Documented from-scratch flow (`uv init --bare`, `uv add "django>=5.2,<6"`, `startproject`, `migrate`, `djust init`) → packages installed, check clean, exit 0. The server serves pages, static files and a WebSocket handshake. The admin changelist returns 200 after migrate.
  - Rerunning `init` leaves every file unchanged.
- [x] Independent adversarial review. Findings and fixes are posted as comments below.

Found while verifying: a bare `uv add django` now resolves Django 6.1, which djust (`<6`) cannot install alongside. The from-scratch docs pin the range.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by johnrtipton** [comment]
## Code review: independent adversarial pass

A separate agent reviewed commits `b6d01e94..d9a89929` against a fresh `django startproject` (Django 5.2.16). Every finding below was reproduced.

### 🔴 Must fix
1. **The admin list and edit pages crash after `djust init`.** The block put `DjustTemplateBackend` first with `APP_DIRS: True`, so it took over the admin's templates. Loading `/admin/auth/user/` then raised `AttributeError: 'DjustTemplateBackend' object has no attribute 'select_template'` (`admin/templatetags/base.py:40`). `djust new --with-db` already has this bug (#2872); `init` would have spread it to every existing project that uses the admin.
2. **Apps listed by AppConfig path were added twice.** With `"channels.apps.ChannelsConfig"` in `INSTALLED_APPS`, the block appended `"channels"` again, and `manage.py check` failed with `Application labels aren't unique`.

### 🟡 Should fix
3. **A settings module could be swapped silently.** A stock-shaped `asgi.py` pointing at `mysite.settings_prod` was replaced with one pointing at `manage.py`'s `mysite.settings`, with no warning. Separately, a leading `1` expression was treated as a docstring.
4. **`config.settings.local` (cookiecutter layout) wasn't refused.** `init` wrote a stray `config/settings/asgi.py` and set a wrong `ASGI_APPLICATION`.
5. **Printed commands weren't shell-quoted.** `pip install djust>=… uvicorn[standard]>=0.30` redirects output in bash and glob-fails in zsh.
6. **`--dry-run` exited 2** when `asgi.py` needed attention.
7. **`djust` was appended as a duplicate** alongside `-e ../djust`, `-e git+…#egg=djust` or archive URLs, and `-r base.txt` includes weren't followed.
8. **The generated Makefile's `PYTHON ?=`** picked up an exported `PYTHON` variable.

### 🟢 Nits
9. CRLF settings files were rewritten with LF endings.
10. Dirty-path errors showed git's quoted and escaped form.
11. The scaffold tree in the docs omitted `templates/`, `AGENTS.md` and `.env.example`.

The reviewer confirmed these claims were accurate:
- the `new` flags table
- `next_steps` output
- stop-on-failure behaviour
- the uncommitted-changes refusal and `--force`
- environment selection rules
- the refusal exit code

**Comment by johnrtipton** [comment]
## Review findings addressed

All fixes are in `d7166468` (code and tests) and `0c59acaa` (docs). Each has a regression test that failed before the fix, and a gate-off mutation of each fix was caught.

| # | Resolution |
|---|---|
| 1 | `init` no longer touches `TEMPLATES`. LiveViews read template source via `loader.get_template(...).template.source` and render it in Rust whichever engine found the file. I confirmed this in a browser: the Your First LiveView counter updates live with no djust entry in `TEMPLATES`. The startproject → `init` test now force-logs in and asserts 200 on `/admin/`, the user changelist and the change page. The framework bug is #2872. "Configure by hand" now marks its optional backend step as unsafe with the admin until #2872 is fixed. |
| 2 | The block matches `entry == app or entry.startswith(app + ".")`. Tests cover AppConfig paths, plus similarly named apps (`djust_components`, `channels_redis`) that must not count. |
| 3 | `asgi.py` is replaced only when its settings string equals the detected module; otherwise it needs ATTENTION and names both modules. A docstring must be a `str` constant. |
| 4 | Refused when the settings file's package is itself nested in a package. The error prints the block for the parent package's `asgi`. |
| 5 | `shlex.join`. |
| 6 | `InitResult.exit_code` returns 0 for dry runs. |
| 7 | Requirement lines are matched by token: editable paths, VCS `#egg=`, archive names with a version stripped, and `name @ url`. `-r`/`--requirement` includes are followed, with a cycle guard. |
| 8 | `PYTHON = .venv/bin/python`. Command-line `make dev PYTHON=…` still overrides it. A test runs `make -n dev` with `PYTHON` exported. |
| 9 | Reads and writes use `newline=""`, and the appended block uses the file's own line ending. |
| 10 | `git status --porcelain -z`, with rename and copy entries handled. |
| 11 | Tree completed. |

**Verification:** full suite after merging `origin/main`: 27,447 passed, 0 failed.
