### PR TITLE
fix(state): preserve private _ attributes across events and reconnects (#627, #611)

### LINKED ISSUE #611: fix: pre-rendered WS reconnect drops _private attributes, skipping mount()
## Bug

When a browser connects via WebSocket with `has_prerendered=true` and saved state exists in the session, `handle_mount` restores state via `safe_setattr(allow_private=False)` and **skips `mount()` entirely**. This means any `_private` attributes initialized in `mount()` are never set, causing `AttributeError` in `get_context_data()`.

## Reproduction

```python
class MyView(LiveView):
    def mount(self, request, **kwargs):
        self._cache = expensive_query()  # Private cached value

    def get_context_data(self, **kwargs):
        return {'items': self._cache}  # AttributeError on WS reconnect
```

1. Load page via HTTP GET (pre-renders, saves state to session)
2. WebSocket connects with `has_prerendered=true`
3. `handle_mount` finds saved state → restores via `safe_setattr(allow_private=False)` → skips `mount()`
4. `_sync_state_to_rust()` → `get_context_data()` → `AttributeError: '_cache'`

## Root Cause

`websocket.py` lines 1208–1231:

```python
if has_prerendered:
    saved_state = await request.session.aget(view_key, {})
    if saved_state:
        for key, value in saved_state.items():
            safe_setattr(self.view_instance, key, value, allow_private=False)  # ← skips _private
        mounted = True  # ← mount() never called

if not mounted:
    await sync_to_async(self.view_instance.mount)(request, **mount_kwargs)
```

Two problems:
1. `allow_private=False` silently drops all `_` prefixed attributes from session restore
2. `mount()` is skipped entirely, so there's no chance to re-initialize them

## Workaround

Add class-level defaults for all private attributes:

```python
class MyView(LiveView):
    _cache = []  # Default so it exists even without mount()
```

## Suggested Fix

Option A (minimal): Change to `allow_private=True` in the state restore path — these are the view's own serialized state, not untrusted input.

Option B (Phoenix parity): Always call `mount()`, then overlay session state. Phoenix LiveView always calls `mount/3` on every connection.

## Affected Version

0.4.0 (and likely 0.3.6+ where pre-rendered state restore was introduced in #542)

### LINKED ISSUE #627: Private (_) attributes are wiped between WebSocket events — breaks event-driven state
## Bug Report

**Severity**: Critical — breaks all event-driven state if developer is unaware of serialization contract

### Symptom

`AttributeError: 'MyView' object has no attribute '_current_step_index'` when an `@event_handler()` method accesses a private attribute that was set in `mount()`.

### Root Cause

djust serializes only **public** (no-underscore prefix) attributes between WebSocket events. Private attributes (`_attr`) exist only within the `mount()` call. When an event fires, djust creates a new view instance and restores only public state — private attributes are not persisted.

This behavior is intentional for heavy objects (QuerySets, model instances) but the failure mode is silent and the error message is misleading — it looks like an uninitialized attribute, not a serialization issue.

### Reproduction

```python
class MyView(BaseLiveView):
    def mount(self, request, **kwargs):
        super().mount(request, **kwargs)
        self._current_step_index = 0  # private — wiped after mount

    @event_handler()
    def next_step(self, **kwargs):
        self._current_step_index += 1  # AttributeError: no attribute '_current_step_index'
```

### Expected Behavior

The documentation should prominently describe the public/private serialization contract. Ideally, the framework should warn at `mount()` time if a private attribute is written that looks like it will be needed in an event handler (heuristic: if it's also read in `get_context_data`).

### Workaround

All state that must persist between events MUST use public attributes (no underscore prefix). Private `_` prefix should only be used for objects intentionally excluded from serialization (QuerySets, model instances).

```python
def mount(self, request, **kwargs):
    super().mount(request, **kwargs)
    self.current_step_index = 0  # ✅ public — persists between events
```

### Documentation Request

This should be prominently documented in the LiveView state management guide with an explicit section titled "Public vs Private Attributes" explaining that `_` attributes are intentionally ephemeral.

### Environment

Discovered during NYC Claims Processing System implementation.

### PR DESCRIPTION
**Pull request by johnrtipton**
## Summary

- **Root cause**: `_save_state_to_session()` persisted only the output of `get_context_data()`, which by design strips `_`-prefixed attributes. This caused private attrs to be wiped on every WebSocket event (#627) and lost during pre-rendered reconnects (#611).
- **Fix**: New `_get_private_state()` / `_restore_private_state()` helpers on `LiveView` collect and restore all `_`-prefixed instance attrs (excluding dunders and base-class internals). Wired into `_save_state_to_session()` (persists under `_private_state` session key), `_load_state_from_session()`, and `RequestMixin._restore_session_state()`.
- **Tests**: 20 new regression tests in `python/tests/test_private_attr_preservation.py` covering event dispatch survival, reconnect survival, sequential events, coexistence with public attrs, None/complex/nested values, dunder exclusion, base-class exclusion, and session round-trip.

## Changed files

- `python/djust/live_view.py` — `_get_private_state()`, `_restore_private_state()`, updated `_save_state_to_session()` and `_load_state_from_session()`
- `python/djust/mixins/request.py` — `_restore_session_state()` now restores private attrs from session
- `python/djust/websocket.py` — reconnect path calls `_restore_private_state()`
- `python/tests/test_private_attr_preservation.py` — 20 new tests
- `CHANGELOG.md` — Fixed entry in [Unreleased]
- `ROADMAP.md` — #627 and #611 marked as shipped

Closes #627. Closes #611.

## Test plan

- [x] All 20 new regression tests pass locally
- [x] Full pytest suite passes (pre-push hook)
- [x] Pre-commit hooks pass (ruff, bandit, detect-secrets)
- [ ] CI passes on GitHub
- [ ] Verify no regressions in existing state management tests

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by johnrtipton — COMMENTED** [review]
## Self-review: fix(state) — private `_` attr preservation (#627, #611)

### Security
- No `mark_safe`, no `@csrf_exempt`, no f-string logging introduced.
- Private state is stored in the Django session (server-side, not exposed to client). The `_private_state` session key contains only serializable Python values — no raw objects or callables.
- The exclusion set (`_BASE_EXCLUSIONS`) prevents framework internals (channel_name, scope, etc.) from being accidentally round-tripped, avoiding state confusion on reconnect.

### Robustness
- `_get_private_state()` uses a try/except around `json.dumps` per-attribute to skip non-serializable values gracefully rather than crashing the save path.
- `_restore_private_state()` uses `setattr` with the stored dict — if the session contains stale keys from a previous code version, they become harmless extra attributes rather than errors.
- Dunder attributes (`__foo__`) are explicitly excluded to avoid corrupting Python internals.

### Test coverage
- 20 tests cover the full matrix: event survival, reconnect survival, sequential events, public/private coexistence, edge types (None, nested dicts/lists, complex values), dunder exclusion, base-class exclusion, and direct session round-trip.
- Tests use the existing `LiveViewTestClient` harness — no mocking of session internals.

### Potential concerns
- If a developer stores a non-JSON-serializable object as a `_` attr, it will be silently dropped from session persistence. This matches the existing behavior for public attrs and is logged at DEBUG level.
- The `_BASE_EXCLUSIONS` set may need updating if new framework-internal `_` attrs are added to LiveView's base classes in the future.

**Comment by johnrtipton** [comment]
## Retrospective

**What shipped:**
- Private `_` attrs now survive WS events, HTTP POST, and pre-rendered reconnects via session persistence
- Two-phase snapshot (`_framework_attrs` → `_snapshot_user_private_attrs`) cleanly separates framework internals from user state
- 20 new tests across HTTP and WS paths

**What went well:**
- Parallel stages (test/review/security) saved ~4 min wall time
- Self-review caught the critical gap: WS reconnect path had no `_restore_private_state()` call — would have shipped #611 unfixed

**What to improve:**
- Implementation agent missed the WS restore path on first pass. The planning stage identified both paths clearly but implementation only wired the HTTP path. Future prompts should include an explicit "verify ALL paths from the plan are wired" checklist item.

**Lessons:**
- The self-review stage pays for itself. The RED finding it caught would have been a shipped regression on the exact issue (#611) the batch was supposed to fix.
